# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/noble64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_PRIORITY=critical DEBIAN_FRONTEND=noninteractive DPKG_FORCE=confold UCF_FORCE_CONFOLD=1 LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
    apt-get update
    apt-get -y dist-upgrade
    apt-get -f -y install ubuntu-desktop
    apt-get -f -y install git libssl-dev build-essential git pkg-config autoconf autoconf-archive libglib2.0-dev libjsoncpp-dev uuid-dev liblz4-dev libcap-ng-dev libxml2-utils python3-minimal python3-dbus python3-docutils python3-jinja2 libxml2-utils libtinyxml2-dev policykit-1 libsystemd-dev python3-systemd
    apt-get -f -y install libnl-3-dev libnl-genl-3-dev protobuf-compiler libprotobuf-dev
    apt-get -f -y remove gnome-initial-setup
    
    systemctl stop gdm3

    groupadd -r openvpn
    useradd -r -s /sbin/nologin -g openvpn openvpn

    git clone https://github.com/OpenVPN/openvpn3-linux.git
    pushd openvpn3-linux
    git pull
    ./bootstrap.sh
    ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-bash-completion
    make
    make install
    popd
    ln -s /usr/lib/python3.*/*-packages/openvpn3 /usr/lib/python3/dist-packages

    openvpn3-admin init-config --write-configs
    systemctl reload dbus

    apt-get -f -y install python3-dbus python3-gi gir1.2-ayatanaappindicator3-0.1 python3-secretstorage python3-setproctitle desktop-file-utils zip

    git clone https://github.com/OpenVPN/openvpn3-indicator.git
    pushd openvpn3-indicator
    git pull
    make all
    make install
    popd

    cp -a /vagrant/provision_root/* /
    update-desktop-database
    glib-compile-schemas /usr/share/glib-2.0/schemas/
    dconf update

    systemctl start gdm3
  SHELL

  config.vm.synced_folder "src/", "/openvpn3-indicator", owner: "ubuntu", group: "ubuntu"
end
