.TH OPENVPN3-INDICATOR "1" "January 2024" "version 0.1"
.SH NAME
openvpn3\-indicator \- Simple GTK indicator GUI for OpenVPN3
.SH SYNOPSIS
.B openvpn3\-indicator
[\-\^\-help|\-\^\-version|\-\^\-silent|\-\^\-verbose|\-\^\-debug]
.SH DESCRIPTION
Some info coming soon.
.PP
More info coming soon.
.SH OPTIONS
.TP
.BR \-h ", " \-\^\-help
Show help and exit
.TP
.BR \-V ", " \-\^\-version
Show program's version number and exit
.TP
.BR \-s ", " \-\^\-silent
Show less information
.TP
.BR \-v ", " \-\^\-verbose
Show more information
.TP
.BR \-d ", " \-\^\-debug
Show debug information
.SH AUTHORS
Grzegorz Gutowski <grzegorz.gutowski@uj.edu.pl>
