.TH OPENVPN3-INDICATOR "1" "January 2024" "version 0.1"
.SH NAME
openvpn3\-indicator \- Simple indicator application for OpenVPN3
.SH SYNOPSIS
.B openvpn3\-indicator
[\-\^\-help|\-\^\-version|\-\^\-silent|\-\^\-verbose|\-\^\-debug]
.SH DESCRIPTION
This is a simple indicator application that controls OpenVPN3 tunnels.
It is based on D-Bus interface provided by OpenVPN3 Linux client.
It is a temporary solution until Network Manager supports OpenVPN3.
.SH OPTIONS
.TP
.BR \-h ", " \-\^\-help
Show help and exit
.TP
.BR \-V ", " \-\^\-version
Show program's version number and exit
.TP
.BR \-s ", " \-\^\-silent
Show less information
.TP
.BR \-v ", " \-\^\-verbose
Show more information
.TP
.BR \-d ", " \-\^\-debug
Show debug information
.SH AUTHORS
Grzegorz Gutowski <grzegorz.gutowski@uj.edu.pl>
