on:
  push:
    branches:
    - main
jobs:
  launchpad:
    name: Deploy to Launchpad
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get -f -y install make devscripts dput dpkg-dev debhelper desktop-file-utils build-essential
    - name: Install GPG Key
      env:
        KEY: ${{ secrets.GPG_LAUNCHPAD_KEY }}
      run: |
        echo "${KEY}" | gpg --import
    - name: Deploy
      run: |
        make -C .launchpad
